### ISSUE TITLE
Add HTTP methods

### ISSUE THREAD

**Issue by aewens** [tildecross/tildex-notify#1]
Add in the ability to interact with this utility using GET and PUSH over HTTP. Preferably with something light-weight like bottle or Flask. Nothing fancy, just the bare minimum to add in this functionality.

**Comment by c-w** [comment]
This can be achieved nicely using the [hug](http://www.hug.rest/website/learn/) library. I'll take a stab at this.

**Comment by aewens** [comment]
@c-w I've haven't come across that package before, I agree that it looks very suitable for this project!
