### ISSUE TITLE
Add OS sockets

### ISSUE THREAD

**Issue by aewens** [tildecross/tildex-notify#2]
Add in the ability to interact with this utility using sockets (assume the other service is running locally). Preferably with something light-weight like the built-in socket package. Nothing fancy, just the bare minimum to add in this functionality.

**Comment by viveksyngh** [comment]
I am interested on working on this one. Can you please provide some explanation on how this utility works and what you want to achieve with socket ?

**Comment by aewens** [comment]
@viveksyngh Sure, so presently this is a bare-bones utility for other services to hook into to pass data to Pushbullet as a note. Right now you either pass in the title and body of the Pushbullet note via calling the script through a shell passing in the title and body parameters or through HTTP passing the variables in through GET queries. 

For this issue I'd like another potentially way to pass data to it from a local OS socket where presumably a parsed string (e.g. JSON) is sent to this utility containing the title and body arguments, then sent to Pushbullet as a note.

**Comment by Abelarm** [comment]
if it is not taken yet I'd like to work on this.

**Comment by aewens** [comment]
@Abelarm There's no active forks right now, so by all means.
