### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by harshanas** [tildecross/tildex-notify#4]

**Comment by aewens** [comment]
Good suggestion!

**Comment by marioecg** [comment]
@harshanas is this issue set just to add a text file named "requirements" in the repository? I'll do it.

**Comment by thiagopaiva99** [comment]
Can you pass the requirements? I can do it too.

**Comment by aewens** [comment]
@thiagopaiva99 It'd be the package in [app.py](https://github.com/tildecross/tildex-notify/blob/master/app.py).

**Comment by thiagopaiva99** [comment]
@aewens done!

**Comment by aewens** [comment]
To clarify, this issue is referring to the requirements.txt file that pip uses for installing packages not in python's standard library. [context](https://pip.readthedocs.io/en/1.1/requirements.html)

**Comment by aewens** [comment]
In light of  changes made in [#1](https://github.com/tildecross/tildex-notify/issues/1), there's another package to include for anyone working on this.

**Comment by c-w** [comment]
Since I added a dependency in #8, I figured I might as well document that dependency via `requirements.txt` so I opened #9.
